[glib]
source.gnome.version = "2.75.0"
pkg.meson = {}

[gtk]
source.gnome.version = "4.8.2"
pkg.meson.args = "-Dmedia-gstreamer=disabled"

[gobject-introspection]
source.gnome.version = "1.74.0"
pkg.meson = {}

[pygobject]
source.gnome.version = "3.42.0"
pkg.meson = {}

[shared-mime-info]
source.url = "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-2.2.tar.bz2"
pkg.meson = {}

[drm-libdrm]
source.url = "https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.114/drm-libdrm-2.4.114.tar.bz2"
pkg.meson = {}

[wayland-protocols]
source.url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.29/wayland-protocols-1.29.tar.bz2"
pkg.meson = {}

[cairo]
# source.url = "https://www.cairographics.org/snapshots/cairo-1.17.4.tar.xz"
source.github.user = "freedesktop"
pkg.meson = {}

[pixman]
source.url = "https://www.cairographics.org/snapshots/pixman-0.33.6.tar.gz"
pkg.autotools = {}

[waybox]
source.github.user = "wizbright"
pkg.meson = {}

[labwc]
source.github.user = "labwc"
pkg.meson = {}

[MPD]
source.github.user = "MusicPlayerDaemon"
source.github.tag = "v0.23.10"
pkg.meson = {}

[foot]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.13.1"
pkg.meson = {}

[tllist]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.1.0"
pkg.meson = {}

[harfbuzz]
source.url = "https://github.com/harfbuzz/harfbuzz/releases/download/5.3.1/harfbuzz-5.3.1.tar.xz"
pkg.meson = {}

[go]
source.url = "https://go.dev/dl/go1.19.3.linux-amd64.tar.gz"
pkg.prebuilt = {}

[fzf]
source.github.user = "junegunn"
source.github.tag = "0.35.1"
pkg.prebuilt = {}

[ghq]
source.url = "https://github.com/x-motemen/ghq/releases/download/v1.3.0/ghq_linux_amd64.zip"
pkg.prebuilt = {}
