[glib]
source.gnome.version = "2.75.0"
pkg.meson = {}

[gtk]
source.gnome.version = "4.8.2"
pkg.meson.args = "-Dmedia-gstreamer=disabled -Dbuild-tests=false"

["gtk+"]
source.gnome.version = "3.24.35"
pkg.meson.args = "-Dwayland_backend=false"

[pango]
source.gnome.version = '1.50.12'
pkg.meson = {}

[openbox]
source.url = "http://openbox.org/dist/openbox/openbox-3.6.1.tar.xz"
pkg.autotools = {}

[obconf]
source.url = "http://openbox.org/dist/obconf/obconf-2.0.4.tar.gz"
pkg.autotools = {}

[atk]
source.gnome.version = "2.38.0"
pkg.meson = {}

[at-spi2-core]
source.url = "https://download.gnome.org/sources/at-spi2-core/2.46/at-spi2-core-2.46.0.tar.xz"
pkg.meson = {}

[librsvg]
source.gnome.version = "2.55.90"
pkg.autotools = {}

[gdk-pixbuf]
source.gnome.version = "2.42.9"
pkg.meson.args = "-Dtests=false -Dman=false"

[gobject-introspection]
source.gnome.version = "1.74.0"
pkg.meson = {}

[pygobject]
source.gnome.version = "3.42.0"
pkg.meson = {}

[shared-mime-info]
source.url = "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-2.2.tar.bz2"
pkg.meson = {}

[drm-libdrm]
source.url = "https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.114/drm-libdrm-2.4.114.tar.bz2"
pkg.meson = {}

[wayland-protocols]
source.url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.29/wayland-protocols-1.29.tar.bz2"
pkg.meson = {}

[cairo]
# source.url = "https://www.cairographics.org/snapshots/cairo-1.17.4.tar.xz"
source.github.user = "freedesktop"
pkg.meson = {}

[pixman]
source.url = "https://www.cairographics.org/snapshots/pixman-0.33.6.tar.gz"
pkg.autotools = {}

[waybox]
source.github.user = "wizbright"
pkg.meson = {}

[labwc]
source.github.user = "labwc"
pkg.meson = {}

[MPD]
source.github.user = "MusicPlayerDaemon"
source.github.tag = "v0.23.10"
pkg.meson = {}

[foot]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.13.1"
pkg.meson = {}

[tllist]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.1.0"
pkg.meson = {}

[harfbuzz]
source.url = "https://github.com/harfbuzz/harfbuzz/releases/download/5.3.1/harfbuzz-5.3.1.tar.xz"
pkg.meson = {}

[go]
source.url = "https://go.dev/dl/go1.19.3.linux-amd64.tar.gz"
pkg.prebuilt = {}

[fzf]
source.github.user = "junegunn"
source.github.tag = "0.35.1"
pkg.prebuilt = {}

[ghq]
source.url = "https://github.com/x-motemen/ghq/releases/download/v1.3.0/ghq_linux_amd64.zip"
pkg.prebuilt = {}

[tigervnc]
source.github.user = "TigerVNC"
source.github.tag = "v1.12.0"
# source.github.tag = "v1.9.0"
pkg.cmake.args = "-DBUILD_VIEWER=OFF"

[fltk]
source.github.user = 'fltk'
source.github.tag = "release-1.3.8"
pkg.cmake = {}

[turbovnc]
source.github.user = "TurboVNC"
source.github.tag = "3.0.2"
pkg.cmake = {}

[neatvnc]
source.github.user = "any1"
source.gethub.tg = 'v0.5.4'
pkg.meson.args = "-Dexamples=true"

[aml]
source.github.user = "any1"
source.github.tag = "v0.2.2"
pkg.meson = {}

[FreeRDP]
source.github.user = "FreeRDP"
source.github.tag = "2.3.0"
pkg.cmake = {}

[xrdp]
source.github.user = "neutrinolabs"
source.github.tag = "v0.9.20"
pkg.prebuilt = {}

[KasmVNC]
source.github.user = "kasmtech"
source.github.tag = "v1.0.0"
pkg.cmake = {}
