[[gnome]]
name = "glib"
major = 2
minor = 75
patch = 0
pkg = "meson"

[[url]]
url = "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-2.2.tar.bz2"
pkg = "meson"

[[url]]
url = "https://www.cairographics.org/releases/cairo-1.16.0.tar.xz"
pkg = "meson"

[[gnome]]
name = "gtk"
major = 4
minor = 8
patch = 2
pkg = "meson"

[[gnome]]
name = "gobject-introspection"
major = 1
minor = 74
patch = 0
pkg = "meson"

[[gnome]]
name = "pygobject"
major = 3
minor = 42
patch = 0
pkg = "meson"

[[github]]
user = "wizbright"
name = "waybox"
pkg = "meson"

[[github]]
user = "labwc"
name = "labwc"
pkg = "meson"

[[url]]
url = "https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.114/drm-libdrm-2.4.114.tar.bz2"
pkg = "meson"

[[url]]
# TODO: move prefix/share/pkgconfig/wayland-protocols.pc to lib64/pkgconfig
url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.29/wayland-protocols-1.29.tar.bz2"
pkg = "meson"

[[github]]
user = "MusicPlayerDaemon"
name = "MPD"
tag = "v0.23.10"
pkg = "meson"

[[codeberg]]
user = "dnkl"
name = "foot"
tag = "1.13.1"
pkg = "meson"

[[url]]
url = "https://github.com/harfbuzz/harfbuzz/releases/download/5.3.1/harfbuzz-5.3.1.tar.xz"
pkg = "meson"

[[codeberg]]
user = "dnkl"
name = "tllist"
tag = "1.1.0"
pkg = "meson"

[[url]]
url = "https://go.dev/dl/go1.19.3.linux-amd64.tar.gz"
pkg = "prebuilt"

[[github]]
user = "junegunn"
name = "fzf"
tag = "0.35.1"
pkg = "prebuilt"

[[url]]
url = "https://github.com/x-motemen/ghq/releases/download/v1.3.0/ghq_linux_amd64.zip"
pkg = "prebuilt"
