[glib]
source.gnome.version = "2.75.2"
pkg.meson = {}

[glibmm]
source.gnome.version = "2.75.0"
pkg.meson = {}

[gtk]
source.gnome.version = "4.9.3"
pkg.meson.args = "-Dmedia-gstreamer=disabled -Dbuild-tests=false"

[gtkmm]
source.gnome.version = "4.9.3"
pkg.meson = {}

["libsigc++"]
source.gnome.version = "3.4.0"
pkg.meson = {}

[mm-common]
source.gnome.version = "1.0.5"
pkg.meson = {}

[pangomm]
source.gnome.version = "2.50.1"
pkg.meson.args = "-Dbuild-documentation=false"

["gtk+"]
source.gnome.version = "3.24.35"
pkg.meson.args = "-Dwayland_backend=false"

[pango]
source.gnome.version = '1.50.12'
pkg.meson = {}

[atk]
source.gnome.version = "2.38.0"
pkg.meson = {}

[at-spi2-core]
source.url = "https://download.gnome.org/sources/at-spi2-core/2.46/at-spi2-core-2.46.0.tar.xz"
pkg.meson = {}

[librsvg]
source.gnome.version = "2.55.90"
pkg.autotools = {}

[gdk-pixbuf]
source.gnome.version = "2.42.9"
pkg.meson.args = "-Dtests=false -Dman=false"

[gobject-introspection]
source.gnome.version = "1.74.0"
pkg.meson = {}

[pygobject]
source.gnome.version = "3.43.1"
pkg.meson = {}

[vte]
source.gnome.version = "0.70.2"
pkg.meson.args = "-Dgtk3=false -Dgtk4=true"

[gnome-terminal]
source.gnome.version = "3.44.1"
pkg.meson = {}

[cairo]
source.gnome.version = "1.17.6"
pkg.meson = {}

[libxslt]
source.gnome.version = "1.1.37"
pkg.cmake.args = "-DLIBXSLT_WITH_PYTHON=OFF"

[libxml2]
source.gnome.version = "2.10.3"
pkg.cmake.args = "-DLIBXML2_WITH_PYTHON=OFF"

[gstreamer]
source.gnome.version = "1.18.0"
pkg.meson = {}
