[openbox]
source.url = "http://openbox.org/dist/openbox/openbox-3.6.1.tar.xz"
pkg.autotools = {}

[obconf]
source.url = "http://openbox.org/dist/obconf/obconf-2.0.4.tar.gz"
pkg.autotools = {}

[fontconfig]
source.url = "https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.bz2"
pkg.meson = {}

[shared-mime-info]
source.url = "https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-2.2.tar.bz2"
pkg.meson = {}

[drm-libdrm]
source.url = "https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.114/drm-libdrm-2.4.114.tar.bz2"
pkg.meson = {}

[wayland-protocols]
source.url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.29/wayland-protocols-1.29.tar.bz2"
pkg.meson = {}

[pipewire]
source.url = "https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.61/pipewire-0.3.61.tar.bz2"
pkg.meson = {}

# [cairo]
# source.url = "https://www.cairographics.org/snapshots/cairo-1.17.4.tar.xz"
# source.github.user = "freedesktop"
# pkg.meson = {}

[pixman]
source.url = "https://www.cairographics.org/snapshots/pixman-0.33.6.tar.gz"
pkg.autotools = {}

[waybox]
source.github.user = "wizbright"
pkg.meson = {}

[labwc]
source.github.user = "labwc"
pkg.meson = {}

[MPD]
source.github.user = "MusicPlayerDaemon"
source.github.tag = "v0.23.10"
pkg.meson = {}

[foot]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.13.1"
pkg.meson = {}

[tllist]
source.codeberg.user = "dnkl"
source.codeberg.tag = "1.1.0"
pkg.meson = {}

[muon]
source.sourcehut.user = "lattis"
source.sourcehut.tag = "0.1.0"
pkg.meson.args = '-Dbestline=disabled'

[harfbuzz]
source.url = "https://github.com/harfbuzz/harfbuzz/releases/download/5.3.1/harfbuzz-5.3.1.tar.xz"
pkg.meson = {}

[tigervnc]
source.github.user = "TigerVNC"
source.github.tag = "v1.12.0"
# source.github.tag = "v1.9.0"
pkg.cmake.args = "-DBUILD_VIEWER=OFF"

[fltk]
source.github.user = 'fltk'
source.github.tag = "release-1.3.8"
pkg.cmake = {}

[turbovnc]
source.github.user = "TurboVNC"
source.github.tag = "3.0.2"
pkg.cmake = {}

[neatvnc]
source.github.user = "any1"
source.gethub.tg = 'v0.5.4'
pkg.meson.args = "-Dexamples=true"

[aml]
source.github.user = "any1"
source.github.tag = "v0.2.2"
pkg.meson = {}

[FreeRDP]
source.github.user = "FreeRDP"
source.github.tag = "2.3.0"
pkg.cmake = {}

[KasmVNC]
source.github.user = "kasmtech"
source.github.tag = "v1.0.0"
pkg.cmake.args = {}

[lua]
source.github.user = "franko"
source.github.head = true
pkg.meson = {}

[lgi]
source.github.user = "lgi-devs"
# source.github.tag = "0.9.2"
pkg.meson = {}

[crystal]
source.github.user = "crystal-lang"
source.github.tag = "1.6.2"
pkg.make.args = "-f Makefile.win verbose=1"

[ruby]
source.github.user = "ruby"
source.github.tag = "v3_1_3"
[ruby.pkg]
custom = '''
win32/configure.bat --prefix={PREFIX}
nmake install
'''

[xfce4-terminal]
source.url = "https://archive.xfce.org/src/apps/xfce4-terminal/1.0/xfce4-terminal-1.0.4.tar.bz2"
pkg.autotools = {}

[blackbox]
source.url = "https://gitlab.gnome.org/raggesilver/blackbox/-/archive/v0.12.2/blackbox-v0.12.2.tar.bz2"
pkg.meson = {}

[libiconv]
source.url = "https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz"
pkg.cmake = {}

[win-iconv]
source.github.user = "win-iconv"
source.github.tag = "v0.0.8"
pkg.cmake = {}

[xz]
source.github.user = "tukaani-project"
source.github.tag = "v5.4.1"
pkg.cmake.args = "-DBUILD_SHARED_LIBS=ON"

[libexpat]
source.github.user = "libexpat"
source.github.tag = "R_2_5_0"
pkg.cmake.cmake_source = "expat"

[mediapipe]
source.github.user = "google"
source.github.tag = "v0.9.1"
pkg.bazel = {}

